# Generated by Django 6.0.7 on 2026-07-18 11:04

import cloudinary_storage.storage
import events.upload_paths
import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200, verbose_name='venue name')),
                ('title', models.CharField(editable=False, max_length=255, verbose_name='title')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('location_url', models.URLField(verbose_name='location URL')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('poster', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='image'), upload_to=events.upload_paths.event_poster_upload_path, validators=[events.validators.validate_event_poster], verbose_name='poster')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('registrations_open', models.BooleanField(default=True, verbose_name='registrations open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['starts_at'], name='events_even_starts__b01102_idx')],
            },
        ),
    ]
