# Generated by Django 6.0.7 on 2026-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum active registrations. Leave blank for no limit.', null=True, verbose_name='capacity'),
        ),
    ]
