# Generated by Django 6.0.7 on 2026-07-15 14:50

import gallery.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=gallery.fields.DynamicCloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
