# Generated by Django 6.0.7 on 2026-07-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_and_gallery_event_link'),
        ('gallery', '0004_cascade_delete_user_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='events.event', verbose_name='event'),
        ),
    ]
