# Generated by Django 6.0.7 on 2026-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_event_capacity_and_gallery_event_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['pin_order', '-created_at'], 'verbose_name': 'gallery item', 'verbose_name_plural': 'gallery items'},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='pin_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Set 1, 2, 3… to show this item first in its section (photos or videos). Leave blank for normal newest-first order.', null=True, verbose_name='pin order'),
        ),
    ]
