# Generated by Django 6.0.7 on 2026-07-21 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryitem_pin_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='pin_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Set 1, 2, 3… to show this item first in its section (photos or videos). Leave blank for normal newest-first order. Maximum three digits (1–999).', null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='pin order'),
        ),
    ]
