# Generated by Django 6.0.7 on 2026-07-21 08:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def clear_duplicate_pin_orders(apps, schema_editor):
    """
    Keep the lowest-pk item for each (media_type, pin_order) pair; clear the rest.

    Required before adding the unique constraint on databases that already have
    duplicate pins from earlier manual edits.
    """
    GalleryItem = apps.get_model("gallery", "GalleryItem")
    seen = set()
    for item in (
        GalleryItem.objects.exclude(pin_order=None)
        .exclude(media_type="")
        .order_by("media_type", "pin_order", "pk")
        .only("pk", "media_type", "pin_order")
    ):
        key = (item.media_type, item.pin_order)
        if key in seen:
            GalleryItem.objects.filter(pk=item.pk).update(pin_order=None)
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_capacity_and_gallery_event_link"),
        ("gallery", "0007_galleryitem_pin_order_max_digits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="pin_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Optional. Set 1, 2, 3… to show this item first in its section "
                    "(photos or videos). Each number can be used only once per section. "
                    "Leave blank for normal newest-first order. Maximum three digits (1–999)."
                ),
                null=True,
                validators=[django.core.validators.MaxValueValidator(999)],
                verbose_name="pin order",
            ),
        ),
        migrations.RunPython(clear_duplicate_pin_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="galleryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("pin_order__isnull", False),
                    models.Q(("media_type", ""), _negated=True),
                ),
                fields=("media_type", "pin_order"),
                name="galleryitem_unique_pin_per_media_type",
            ),
        ),
    ]
