# Generated by Django 6.0.7 on 2026-07-14 14:44

import pages.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Displayed in the home page carousel.', upload_to=pages.upload_paths.home_carousel_upload_path)),
                ('alt_text', models.CharField(help_text='Describe the image for screen readers and SEO.', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional short text shown over the slide.', max_length=255)),
                ('slide_type', models.CharField(choices=[('event_highlight', 'Event highlight'), ('generic', 'Generic')], default='generic', help_text='Helps you organise slides in the admin panel.', max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive slides are hidden from the public home page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'carousel slide',
                'verbose_name_plural': 'carousel slides',
                'ordering': ['order'],
            },
        ),
    ]
