# Generated by Django 6.0.7 on 2026-07-15 12:49

import django.core.validators
import pages.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarouselslide',
            name='image',
            field=models.ImageField(help_text='Displayed in the home page carousel.', upload_to=pages.upload_paths.home_carousel_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'dib', 'gif', 'jfif', 'jpe', 'jpeg', 'jpg', 'png', 'apng', 'tif', 'tiff', 'webp', 'heic', 'heif'])]),
        ),
    ]
