# Generated by Django 6.0.7 on 2026-07-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_allow_heic_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarouselslide',
            name='slide_type',
        ),
    ]
