# Generated by Django 6.0.7 on 2026-07-15 13:32

import pages.upload_paths
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_homecarouselslide_slide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarouselslide',
            name='image',
            field=models.ImageField(help_text='Displayed in the home page carousel.', upload_to=pages.upload_paths.home_carousel_upload_path, validators=[pages.validators.validate_carousel_image]),
        ),
    ]
