# Generated by Django 6.0.7 on 2026-07-20 13:33

import pages.upload_paths
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_update_carousel_image_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOrganiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Short role label, e.g. Founder or Sound Engineer.', max_length=120)),
                ('bio', models.TextField(help_text='Short biography shown under the name.')),
                ('initials', models.CharField(help_text='Shown as a placeholder when no photo is uploaded (e.g. D, R, De).', max_length=3)),
                ('photo', models.ImageField(blank=True, help_text='Optional profile photo. Replacing it deletes the previous file.', upload_to=pages.upload_paths.about_organiser_upload_path, validators=[pages.validators.validate_organiser_photo])),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive organisers are hidden from the public About page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organiser',
                'verbose_name_plural': 'organisers',
                'ordering': ['order'],
            },
        ),
    ]
