# Generated by Django 6.0.7 on 2026-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_about_organisers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutorganiser',
            name='photo_focus_x',
            field=models.FloatField(default=50, help_text='Horizontal focal point as a percentage (0 = left, 100 = right).', verbose_name='photo focus X'),
        ),
        migrations.AddField(
            model_name='aboutorganiser',
            name='photo_focus_y',
            field=models.FloatField(default=50, help_text='Vertical focal point as a percentage (0 = top, 100 = bottom).', verbose_name='photo focus Y'),
        ),
    ]
