# Generated by Django 6.0.7 on 2026-07-16 23:14

import gallery.fields
import gallery.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='cover_image',
            field=gallery.fields.DynamicCloudinaryField(blank=True, max_length=255, null=True, validators=[gallery.validators.validate_gallery_file_size, gallery.validators.validate_gallery_file_type], verbose_name='cover image'),
        ),
    ]
