# Generated by Django 6.0.7 on 2026-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitypost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='cover_focus_x',
            field=models.FloatField(default=50, help_text='Horizontal focal point as a percentage (0 = left, 100 = right).', verbose_name='cover focus X'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='cover_focus_y',
            field=models.FloatField(default=50, help_text='Vertical focal point as a percentage (0 = top, 100 = bottom).', verbose_name='cover focus Y'),
        ),
    ]
