# Generated by Django 6.0.7 on 2026-07-14 14:12

import accounts.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_age_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.upload_paths.profile_picture_upload_path),
        ),
    ]
