# Generated by Django 6.0.7 on 2026-07-15 18:14

import accounts.upload_paths
import accounts.validators
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_preferred_genres_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='image'), upload_to=accounts.upload_paths.profile_picture_upload_path, validators=[accounts.validators.validate_profile_picture]),
        ),
    ]
