# Generated by Django 6.0.7 on 2026-07-17 10:42

import django.core.validators
from django.db import migrations, models

# Genres removed from MusicGenre choices — strip from existing JSON lists.
REMOVED_GENRES = frozenset({"irish_traditional", "ska", "world"})


def purge_removed_genres(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.iterator():
        genres = user.preferred_genres or []
        cleaned = [code for code in genres if code not in REMOVED_GENRES]
        if cleaned != genres:
            user.preferred_genres = cleaned
            user.save(update_fields=["preferred_genres"])


def noop_reverse(apps, schema_editor):
    """Removed genre codes cannot be restored meaningfully."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_picture_heic_and_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                verbose_name="experience level",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="other_genre",
            field=models.CharField(
                blank=True,
                help_text="Specify your genre if you selected 'Other'.",
                max_length=30,
                verbose_name="other genre",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_link",
            field=models.URLField(
                blank=True,
                help_text=(
                    "Optional link to Instagram, Spotify, YouTube, or another "
                    "social / music profile."
                ),
                verbose_name="social / music link",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How many years you have been playing (0–80).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="years of experience",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Used to send you an automatic invitation to the community "
                    "WhatsApp group."
                ),
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Enter a valid phone number using digits only, with "
                            "an optional leading + for the country code "
                            "(e.g. +353871234567)."
                        ),
                        regex=r"^\+?[0-9]{7,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.RunPython(purge_removed_genres, noop_reverse),
    ]
