# Generated by Django 6.0.7 on 2026-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sociallink_and_remove_user_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_member_badge',
            field=models.BooleanField(default=False, help_text="If enabled, shows 'Member' badge instead of 'New Member' even if joined less than 30 days ago.", verbose_name='force Member badge'),
        ),
    ]
