# Generated by Django 6.0.7 on 2026-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_unique_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_send_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many verification emails have been sent while this account is still unverified. After the limit, the member must contact JamSession Lab for manual activation.', verbose_name='verification emails sent'),
        ),
    ]
