# Generated by Django 6.0.7 on 2026-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_email_verification_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_focus_x',
            field=models.FloatField(default=50, help_text='Horizontal focal point as a percentage (0 = left, 100 = right).', verbose_name='profile picture focus X'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_focus_y',
            field=models.FloatField(default=50, help_text='Vertical focal point as a percentage (0 = top, 100 = bottom).', verbose_name='profile picture focus Y'),
        ),
    ]
