# Generated by Django 6.0.7 on 2026-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_profile_picture_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email awaiting confirmation. Empty when no change is in progress.', max_length=254, verbose_name='pending email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_age_publicly',
            field=models.BooleanField(default=False, help_text='If enabled, your age (not date of birth) is visible on your public profile.', verbose_name='show age publicly'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_location_publicly',
            field=models.BooleanField(default=False, help_text='If enabled, your town and county are visible on your public profile.', verbose_name='show location publicly'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone_publicly',
            field=models.BooleanField(default=False, help_text='If enabled, your phone number is visible on your public profile.', verbose_name='show phone publicly'),
        ),
    ]
