# Generated by Django 6.0.7 on 2026-07-20 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_privacy_flags_and_pending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Private contact number. Never shown on the public profile — used only to send an automatic invitation to the community WhatsApp group.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, with an optional leading + for the country code (e.g. +353871234567).', regex='^\\+?[0-9]{7,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_phone_publicly',
            field=models.BooleanField(default=False, help_text='Unused: phone numbers are never shown on public profiles. Kept for database compatibility.', verbose_name='show phone publicly'),
        ),
    ]
