# Generated by Django 6.0.7 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_phone_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_from_members_list',
            field=models.BooleanField(default=False, help_text='If enabled, this user is omitted from the community members sidebar. They can still log in and use the site normally.', verbose_name='hide from members list'),
        ),
    ]
