"""
Django settings for jamsession project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if not os.environ.get("SECRET_KEY"):
    raise ImproperlyConfigured(
        "SECRET_KEY is not set. Configure it in your .env file."
    )

SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
# Default False — local development must set DJANGO_DEBUG=True explicitly in .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# Comma-separated hostnames, e.g. "jamsessionlab.ie,www.jamsessionlab.ie".
# Local fallback applies only when DEBUG is on and the env var is unset.
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in _allowed_hosts_env.split(",") if host.strip()
    ]
elif DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
else:
    ALLOWED_HOSTS = []

# Comma-separated origins for CSRF (scheme + host), e.g.
# "https://jamsessionlab.ie,https://www.jamsessionlab.ie,https://app.onrender.com".
_csrf_trusted_origins_env = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
if _csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in _csrf_trusted_origins_env.split(",")
        if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",
    "adminsortable2",
    "accounts.apps.AccountsConfig",
    "pages",
    "gallery",
    "community",
    "events.apps.EventsConfig",
    "registrations.apps.RegistrationsConfig",
]

AUTH_USER_MODEL = "accounts.User"

# Public authentication pages (accounts app).
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


def gallery_pending_admin_link(request):
    from django.urls import reverse

    return reverse("admin:gallery_galleryitem_changelist") + "?status__exact=pending"


def community_pending_admin_link(request):
    from django.urls import reverse

    return (
        reverse("admin:community_communitypost_changelist") + "?status__exact=pending"
    )


UNFOLD = {
    "SITE_TITLE": "JamSession Lab Admin",
    "SITE_HEADER": "JamSession Lab",
    "SITE_SYMBOL": "music_note",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Home"),
                "separator": True,
                "items": [
                    {
                        "title": _("Carousel slides"),
                        "icon": "view_carousel",
                        "link": reverse_lazy(
                            "admin:pages_homecarouselslide_changelist"
                        ),
                    },
                    {
                        "title": _("Organisers"),
                        "icon": "groups",
                        "link": reverse_lazy(
                            "admin:pages_aboutorganiser_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Gallery"),
                "separator": True,
                "items": [
                    {
                        "title": _("All media"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:gallery_galleryitem_changelist"),
                    },
                    {
                        "title": _("Pending approval"),
                        "icon": "pending",
                        "link": gallery_pending_admin_link,
                    },
                ],
            },
            {
                "title": _("Community"),
                "separator": True,
                "items": [
                    {
                        "title": _("All posts"),
                        "icon": "forum",
                        "link": reverse_lazy(
                            "admin:community_communitypost_changelist"
                        ),
                    },
                    {
                        "title": _("Pending approval"),
                        "icon": "pending",
                        "link": community_pending_admin_link,
                    },
                    {
                        "title": _("All comments"),
                        "icon": "chat",
                        "link": reverse_lazy(
                            "admin:community_communitycomment_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Events"),
                "separator": True,
                "items": [
                    {
                        "title": _("All events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:events_event_changelist"),
                    },
                    {
                        "title": _("Registrations"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy(
                            "admin:registrations_eventregistration_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Users"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.EmailVerificationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jamsession.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "community.context_processors.community_members",
            ],
        },
    },
]

WSGI_APPLICATION = "jamsession.wsgi.application"


# Database — PostgreSQL (Neon), configured via DATABASE_URL in .env.
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if not os.environ.get("DATABASE_URL"):
    raise ImproperlyConfigured(
        "DATABASE_URL is not set. Configure it in your .env file."
    )

TESTING = "test" in sys.argv

_database_url = os.environ["DATABASE_URL"]
if TESTING:
    # The test runner drops the test database at teardown, which fails through
    # Neon's connection pooler (PgBouncer keeps a server session open). Tests
    # therefore use the direct endpoint (same host without "-pooler") and no
    # persistent connections.
    _database_url = _database_url.replace("-pooler", "", 1)

DATABASES = {
    "default": dj_database_url.parse(
        _database_url,
        # Reuse connections for 10 minutes instead of opening a new one per
        # request — important with a remote database.
        conn_max_age=0 if TESTING else 600,
        # Verify reused connections are still alive (Neon suspends idle
        # compute, which can drop connections).
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/Dublin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "jamsession" / "static",
]

# User-uploaded media (profile pictures, gallery, etc.) — stored on Cloudinary
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUD_NAME"),
    "API_KEY": os.environ.get("API_KEY"),
    "API_SECRET": os.environ.get("API_SECRET"),
    "PREFIX": "",
}

# CloudinaryField uses the Cloudinary SDK directly (not django-cloudinary-storage).
# Ensure credentials are configured at startup, same as for ImageField uploads.
import cloudinary

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"],
    secure=True,
)

# Email — transactional mail via Resend.
#
# Preferred on Render: RESEND_API_KEY → HTTPS API (api.resend.com). Outbound
# SMTP often times out on the free instance; HTTPS avoids that.
# SMTP settings below remain as a local/fallback path when no API key is set.
#
# EMAIL_TIMEOUT applies to both Resend HTTP calls and SMTP connect/send.
#
# Override EMAIL_BACKEND via env for emergency fallback, e.g.:
#   EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
#
# Sender domain jamsessionlab.ie must be verified in the Resend dashboard
# (SPF/DKIM DNS records) before production delivery works.
# TODO: replace background-thread delivery with a proper task queue
# (Celery / Django-Q / RQ) when a broker is available on Render.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
RESEND_API_URL = os.environ.get(
    "RESEND_API_URL",
    "https://api.resend.com/emails",
)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.resend.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "resend")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", RESEND_API_KEY)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
# Fail fast if SMTP/API is unreachable (Render free → SMTP hangs).
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "JamSession Lab <staff@jamsessionlab.ie>",
)
# Inbox that receives public contact-form messages (must be deliverable —
# see Resend sending + email forwarding / inbound docs).
CONTACT_EMAIL = os.environ.get("CONTACT_EMAIL", "staff@jamsessionlab.ie").strip()

# Invitation link to the community WhatsApp group, shown after registration
# and included in the welcome email. Replace with the real group link.
WHATSAPP_COMMUNITY_LINK = "https://chat.whatsapp.com/JzOeCrY2Lb96ag6zze1qhb"


STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "jamsession.storage.NonStrictStaticFilesStorage",
    },
}

STATICFILES_STORAGE = "jamsession.storage.NonStrictStaticFilesStorage"

MEDIA_URL = "/media/"

# Align request-body / in-memory upload limits with the highest business
# upload cap (gallery / community: 100 MB). Without this, Django rejects
# bodies over the 2.5 MB default with a raw RequestDataTooBig before forms run.
DATA_UPLOAD_MAX_MEMORY_SIZE = 104_857_600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104_857_600  # 100 MB

# Trust X-Forwarded-Proto from the reverse proxy (e.g. Render). Harmless
# locally when the header is absent.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Production-only HTTPS hardening. Left off when DEBUG=True so local
# development on http://127.0.0.1:8000 keeps working.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
