# Generated by Django 6.0.7 on 2026-07-18 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20, verbose_name='RSVP status')),
                ('join_open_mic', models.BooleanField(default=False, verbose_name='join Open Mic')),
                ('join_open_jam', models.BooleanField(default=False, verbose_name='join Open Jam')),
                ('wants_originals_in_jam', models.BooleanField(blank=True, null=True, verbose_name='wants originals in jam')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('instruments_snapshot', models.JSONField(blank=True, default=list, verbose_name='instruments snapshot')),
                ('experience_level_snapshot', models.CharField(blank=True, max_length=20, verbose_name='experience level snapshot')),
                ('attendance_status', models.CharField(choices=[('unknown', 'Unknown'), ('attended', 'Attended'), ('no_show', 'No-show')], default='unknown', max_length=20, verbose_name='attendance status')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registered at')),
                ('first_registered_at', models.DateTimeField(verbose_name='first registered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'event registration',
                'verbose_name_plural': 'event registrations',
                'ordering': ['registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('song_key', models.CharField(max_length=50, verbose_name='key')),
                ('basic_chords', models.TextField(verbose_name='basic chords')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='registrations.eventregistration', verbose_name='registration')),
            ],
            options={
                'verbose_name': 'registration song',
                'verbose_name_plural': 'registration songs',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'rsvp_status'], name='registratio_event_i_6a0e8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
    ]
